" My vimrc

scriptencoding utf-8

" dein{{{1
" dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

let s:cache_home = empty($XDG_CACHE_HOME) ? expand('~/.cache') : $XDG_CACHE_HOME
let s:dein_dir = s:cache_home . '/dein'
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if !isdirectory(s:dein_repo_dir)
  call system('git clone https://github.com/Shougo/dein.vim ' . shellescape(s:dein_repo_dir))
endif

" Required:
execute 'set runtimepath+=' . s:dein_repo_dir

" Required:
if dein#load_state(s:dein_dir)  " 失敗したら
  call dein#begin(s:dein_dir)

  call dein#load_toml('~/.vim/dein.toml', {'lazy': 0})
  call dein#load_toml('~/.vim/dein_lazy.toml', {'lazy': 1})
  call dein#load_toml('~/.vim/dein_deoplete.toml', {'lazy': 1})
  call dein#load_toml('~/.vim/dein_lsp.toml', {'lazy': 0})

  " Required:
  call dein#end()
  call dein#save_state()
endif

let g:dein#enable_notification = 1
let g:dein#install_log_filename = s:dein_dir . '/dein.log'

" Required:
filetype plugin indent on
syntax enable

" Note: In Vim initializing, you must call the
" "hook_post_source" hooks manually in |VimEnter| if needed.
autocmd VimEnter * call dein#call_hook('post_source')

" End dein Scripts-------------------------
" }}}

" 基本設定 {{{1
augroup MyAutoCmd
  autocmd!
augroup END

" 行番号を表示
set number
set relativenumber

" コマンドラインを便利に
set wildmenu

" 大文字小文字を区別しない
set ignorecase
set smartcase

" 検索結果
set hlsearch
set incsearch

" ビープ音をvisualbellに
set visualbell

" マウス
set mouse=a

" insertモードでEmacs風のカーソル移動
inoremap <C-f> <Right>
inoremap <C-b> <Left>

" インデントの深さ
set tabstop=4
set softtabstop=4
set shiftwidth=4
" ソフトタブ
set expandtab

augroup MyAutoCmd
  autocmd FileType ruby setlocal tabstop=2 softtabstop=2 shiftwidth=2
  autocmd FileType tex setlocal tabstop=2 softtabstop=2 shiftwidth=2
  autocmd FileType html setlocal tabstop=2 softtabstop=2 shiftwidth=2
  autocmd FileType eruby setlocal tabstop=2 softtabstop=2 shiftwidth=2
  autocmd FileType haml setlocal tabstop=2 softtabstop=2 shiftwidth=2
  autocmd FileType sh setlocal tabstop=2 softtabstop=2 shiftwidth=2
augroup END

" いらないキーを無効化
nnoremap ZZ <Nop>
nnoremap ZQ <Nop>
nnoremap Q <Nop>

" spell check
set spelllang=en,cjk

if has('nvim')
  set inccommand=split
endif

" 保存しなくてもバッファ間の移動ができるように
set hidden
